version: 2

updates:
  - package-ecosystem: docker
    directory: "/test-normal-tag"
    schedule:
      interval: "daily"

  - package-ecosystem: docker
    directory: "/test-word-tag"
    schedule:
      interval: "daily"

  - package-ecosystem: docker
    directory: "/test-no-update"
    schedule:
      interval: "daily"