version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/test1"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/test1"
    schedule:
      interval: "daily"
