# dependabot should not update this to ashnam/nginx:1.22.0 or ashnam/nginx:2.0
# it should instead update this to 1.21.6-1
# if 1.21.7 exists however, it would update to that
FROM docker.io/ashnam/nginx:1.21.7-1
